---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: slv-k8s-operator
  namespace: slv
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slv-k8s-operator-clusterrole
rules:
  - apiGroups: ["slv.oss.amagi.com"]
    resources: ["slvs"]
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - "create"
      - "get"
      - "list"
      - "update"
      - "delete"
      - "watch"
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs:
      - "get"
      - "create"
      - "update"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slv-k8s-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: slv-k8s-operator
  namespace: slv
roleRef:
  kind: ClusterRole
  name: slv-k8s-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slv-k8s-operator
  namespace: slv
  labels:
    app: slv-k8s-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slv-k8s-operator
  template:
    metadata:
      labels:
        app: slv-k8s-operator
    spec:
      serviceAccountName: slv-k8s-operator
      containers:
      - name: slv-k8s-operator
        image: ghcr.io/amagioss/slv:latest
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi" # 500Mi of memory should be a sufficient for most cases.
        env:
          - name: SLV_MODE
            value: "k8s_operator"
          # - name: SLV_ENV_SECRET_KEY
          #   valueFrom: # SLV Environment Secret Key from K8s Secret
          #     secretKeyRef:
          #       name: slv # Name of K8s Secret
          #       key: SecretKey  # Key within K8s Secret
          # - name: SLV_ENV_SECRET_BINDING
          #   valueFrom: # SLV Environment Secret Binding from K8s ConfigMap
          #     configMapKeyRef:
          #       name: slv # Name of K8s ConfigMap
          #       key: SecretBinding  # Key within K8s ConfigMap
